import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Script cliente: renombra y elimina temporalmente window.ethereum para evitar auto-connect de MetaMask durante pruebas */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  if (typeof window !== 'undefined' && window.ethereum) {
                    // Guardar backup para poder restaurarlo más tarde si es necesario
                    try { window.__ethereum_backup_for_local_dev = window.ethereum; } catch(e) {}
                    try { delete window.ethereum; } catch(e) {}
                    console.info('[dev] window.ethereum temporarily removed to force using Freighter only');
                  }
                } catch(e) {
                  // no-op
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}